<?php
/**
 * Custom block styles and pattern categories.
 *
 * Styles are registered with `style_data` (theme.json-shaped objects) so their
 * CSS is generated by WordPress alongside the global stylesheet and uses the
 * same presets as theme.json. Requires WordPress 6.6+.
 *
 * @package Serif
 */

namespace Serif;

/**
 * Register block styles.
 */
function register_block_styles() {
	// Quote.
	register_block_style(
		'core/quote',
		array(
			'name'       => 'large',
			'label'      => __( 'Large', 'serif' ),
			'style_data' => array(
				'typography' => array(
					'fontSize'   => 'var(--wp--preset--font-size--x-large)',
					'lineHeight' => '1.4',
				),
				'color'      => array(
					'background' => 'transparent',
				),
				'spacing'    => array(
					'padding' => array(
						'top'    => '8px',
						'right'  => '0',
						'bottom' => '8px',
						'left'   => '32px',
					),
				),
			),
		)
	);

	register_block_style(
		'core/quote',
		array(
			'name'       => 'pull-quote',
			'label'      => __( 'Pull quote', 'serif' ),
			'style_data' => array(
				'typography' => array(
					'fontFamily' => 'var(--wp--preset--font-family--ibm-plex-sans)',
					'fontSize'   => 'var(--wp--preset--font-size--x-large)',
					'fontStyle'  => 'normal',
					'fontWeight' => '600',
					'lineHeight' => '1.3',
					'textAlign'  => 'center',
				),
				'color'      => array(
					'background' => 'transparent',
				),
				'border'     => array(
					'left'   => array( 'width' => '0' ),
					'top'    => array(
						'color' => 'var(--wp--preset--color--primary)',
						'style' => 'solid',
						'width' => '2px',
					),
					'bottom' => array(
						'color' => 'var(--wp--preset--color--primary)',
						'style' => 'solid',
						'width' => '2px',
					),
				),
				'spacing'    => array(
					'padding' => array(
						'top'    => '32px',
						'right'  => '0',
						'bottom' => '32px',
						'left'   => '0',
					),
				),
			),
		)
	);

	// Separator. Core already provides "wide" and "dots".
	register_block_style(
		'core/separator',
		array(
			'name'       => 'narrow',
			'label'      => __( 'Narrow', 'serif' ),
			'style_data' => array(
				'dimensions' => array( 'minHeight' => '0' ),
				'css'        => 'width:80px;max-width:80px;margin-left:auto;margin-right:auto;',
			),
		)
	);

	register_block_style(
		'core/separator',
		array(
			'name'       => 'thick',
			'label'      => __( 'Thick', 'serif' ),
			'style_data' => array(
				'border' => array(
					'top' => array(
						'color' => 'var(--wp--preset--color--foreground)',
						'style' => 'solid',
						'width' => '4px',
					),
				),
			),
		)
	);

	// Cover.
	register_block_style(
		'core/cover',
		array(
			'name'       => 'gradient',
			'label'      => __( 'Gradient overlay', 'serif' ),
			'style_data' => array(
				'css' => '& .wp-block-cover__background{background:linear-gradient(to top, rgba(28,27,26,.9) 0%, rgba(28,27,26,.4) 60%, rgba(28,27,26,0) 100%) !important;opacity:1 !important;}',
			),
		)
	);

	register_block_style(
		'core/cover',
		array(
			'name'       => 'overlay-dark',
			'label'      => __( 'Dark overlay', 'serif' ),
			'style_data' => array(
				'css' => '& .wp-block-cover__background{background-color:var(--wp--preset--color--dark) !important;opacity:.85 !important;}',
			),
		)
	);

	// Image. Core already provides "rounded".
	register_block_style(
		'core/image',
		array(
			'name'       => 'shadow',
			'label'      => __( 'Shadow', 'serif' ),
			'style_data' => array(
				'css' => '& img{box-shadow:0 8px 24px rgba(28,27,26,.18);}',
			),
		)
	);

	register_block_style(
		'core/image',
		array(
			'name'       => 'frame',
			'label'      => __( 'Frame', 'serif' ),
			'style_data' => array(
				'css' => '& img{padding:8px;background:var(--wp--preset--color--white);border:1px solid var(--wp--preset--color--border);}',
			),
		)
	);
}
add_action( 'init', __NAMESPACE__ . '\\register_block_styles' );

/**
 * Register pattern categories.
 */
function register_pattern_categories() {
	$categories = array(
		'serif-layout' => __( 'Serif: Layout', 'serif' ),
		'serif-hero'   => __( 'Serif: Hero', 'serif' ),
		'serif-media'  => __( 'Serif: Media', 'serif' ),
	);

	foreach ( $categories as $slug => $label ) {
		register_block_pattern_category( $slug, array( 'label' => $label ) );
	}
}
add_action( 'init', __NAMESPACE__ . '\\register_pattern_categories' );
